### PR TITLE
Fix Symfony3 is now the latest release

### PR DESCRIPTION
**Pull request by ogizanagi**
Symfony 3 is now the latest release. :tada: 

Fix the following issue:

```bash
symfony new test

 Downloading Symfony...

    4.93 MB/4.93 MB ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100%

 Preparing project...

PHP Warning:  require(/Users/Ogi/test/app/SymfonyRequirements.php): failed to open stream: No such file or directory in phar:///usr/local/bin/symfony/src/Symfony/Installer/DownloadCommand.php on line 265

Warning: require(/Users/Ogi/test/app/SymfonyRequirements.php): failed to open stream: No such file or directory in phar:///usr/local/bin/symfony/src/Symfony/Installer/DownloadCommand.php on line 265
PHP Fatal error:  require(): Failed opening required '/Users/Ogi/test/app/SymfonyRequirements.php' (include_path='.:/usr/local/php5/lib/php') in phar:///usr/local/bin/symfony/src/Symfony/Installer/DownloadCommand.php on line 265

Fatal error: require(): Failed opening required '/Users/Ogi/test/app/SymfonyRequirements.php' (include_path='.:/usr/local/php5/lib/php') in phar:///usr/local/bin/symfony/src/Symfony/Installer/DownloadCommand.php on line 265
```

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Are you using the most recent release of the installer?

**Comment by ogizanagi** [comment]
@javiereguiluz : I'm currently using the master branch of the repository.

**Comment by javiereguiluz** [comment]
OK. I'm going to merge and release a new version. Thanks for fixing this issue @ogizanagi.

**Comment by iagomelanias** [comment]
Same problem here. I also can't run the command `symfony new [name] 3.0`.

**Comment by ogizanagi** [comment]
@javiereguiluz : tests will need to be updated, but I guess this could be done after a new release.

**Comment by javiereguiluz** [comment]
@iagomelanias try excuting the command again and it should work now.

**Comment by pounard** [comment]
Don't know if this is related, but I had similar but not exactly the same kind of errors, trying to ugprade. It seems that the generated composer.json specifies app/Kernel.php in autoload files, it's being loaded prior to the bootstrap.php.cache file generation, so most of the class chain required by the kernel is declared while the Symfony\Component\ClassLoader\ClassCollectionLoader is trying to generate the cache file. Because those class are declared, they are being ignored and not dumped: on next run, an incomplete bootstrap.php.cache file is loaded and generate PHP fatal errors due to missing interfaces.

**Pull request merged**
