### PR TITLE
Check the installer version

### PR DESCRIPTION
**Pull request by Pierstoval**
This is a *basic* implementation that will compare the local version with the distant one.

Actually, this does the check on every command, but I'd like to discuss about how we could improve this, because I don't know what kind of implications there is in requesting the version on each command...

### CODE REVIEW

**Comment by stof** [comment]
#221 has the advantage of skipping this warning for the self-update command itself

**Comment by Pierstoval** [comment]
No problem for keeping #221 ;)

**Comment by javiereguiluz** [comment]
I'm closing this in favor of #221. The other one was submitted earlier and the code looks a bit simpler. Anyway, thanks @Pierstoval for your help with this. As always, your work is really appreciated!

**Comment by Pierstoval** [comment]
"Earlier" is just about some few minutes :laughing: But yeah I should have waited before submitting a PR for nothing :)
Thanks ;)

**Pull request closed without merging**
