### PR TITLE
Simplify code

### PR DESCRIPTION
**Pull request by fabpot**
Unless I'm missing something, this code always returns tgz.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Indeed it looks like it's useless ... but this code chooses the minimum size file compatible with your operating system. So it chooses `.zip`when using the installer on Windows systems.

Our original idea was that someday Symfony would publish for example `.bz2` packages and then we'd add that format to the list.

**Comment by fabpot** [comment]
If you add support to `bz2`, then hardcode `bz2` as it's going to always be returned. Are you sure about zip on Windows?

**Comment by jzawadzki** [comment]
I've tested it just now on `Win10/php 7.0.12` and Installer has downloaded `.tgz`

**Comment by xabbuh** [comment]
IIRC the behaviour depends on your Windows installation (i.e. version of the OS and which additional tools are installed). So on many systems the gzipped tar would still be used, but the code as is allows Distill to fall back to zip for some Windows systems.

**Comment by javiereguiluz** [comment]
Let's close this old PR because the ZIP file is downloaded under some circumstances on Windows.

**Pull request closed without merging**
