### PR TITLE
Keep .gitignore files in sync

### PR DESCRIPTION
**Pull request by ogizanagi**
This is only a quick fix regarding the issue mentioned in #211 , and the few recent issues related:

- #217
- https://github.com/symfony/symfony/issues/16815

### CODE REVIEW

**Comment by Pierstoval** [comment]
So you just wrote the "raw" .gitignore files that are used in both 2.x and 3.x branches then, it sounds better :+1:

**Comment by ogizanagi** [comment]
@Pierstoval : Yes, and your comment also made me think the array syntax is useless now, so here is the nowdoc alternative.
Even if nothing is done about #211, it is then more straightforward to update.

**Comment by Pierstoval** [comment]
I love this string format even if it looks a bit ugly in the first sight :D I'm :+1: on this

**Comment by javiereguiluz** [comment]
I'm not sure about the new format. I think it's a bit ugly :(

**Comment by ogizanagi** [comment]
@javiereguiluz: I can make those two ugly strings constants or dedicated files tonight if you think it's better. But I think the string format should be kept over the array entries for maintainability.

**Comment by ogizanagi** [comment]
@javiereguiluz : PR updated with two new proposals:

- 091505d avoid ugly strings by adding both `.gitignore` files as resources in the phar archive (cannot let the leading dot, because box does not allow easily to not ignore dot files currently).
- 809cd1b retrieve `.gitinore` files directly from github. (If no connection available, it should generate an empty `.gitignore` file)  
IMHO, that's not the best option for the future, because I'd like to avoid extra HTTP requests, in case we add cache later, and allow to use the installer without any connection.  
So it doesn't fully solved #211, and I still think those files should be part of the generated archive.

**Comment by javiereguiluz** [comment]
@ogizanagi thanks for working on this. I like the last proposal that retrieves the `.gitignore` from GitHub.

In order to solve the original error, I'm trying to modify the build script to maintain the `.gitignore` file (see https://github.com/sensiolabs/SensioDistributionBundle/pull/246). If this change gets approved, we'll have the `.gitignore` for **new** packages only, because the old packages won't be released.

That's why I ask you: should we add a check in your code to verify if the `.gitignore` file exists before trying to download it from GitHub? Thanks!

**Comment by weaverryan** [comment]
:+1: for your idea Javier. I was wondering (until you explained it) why we weren't just using the `.gitignore` from the SE.

**Comment by ogizanagi** [comment]
@javiereguiluz: Done.

**Pull request merged**
