### PR TITLE
Issue #42 A better way to manage the version on install

### PR DESCRIPTION
**Pull request by Pierstoval**

### CODE REVIEW

**Comment by Pierstoval** [comment]
Hi @xabbuh , is this PR ok for merging ? :smile:

**Comment by xabbuh** [comment]
@Pierstoval I'm not the one to decide, but to me it looks ready. :)

**Comment by Pierstoval** [comment]
Fine, thanks ! We'll just wait for it to be merged, I think it's an awesome feature !
I just installed a new SF2.6 app some days ago and was surprised that I couldn't do "new app/ 2.6" , when I remembered that it was only available in my local machine :laughing:

**Comment by javiereguiluz** [comment]
Thanks @Pierstoval for working on this feature. The Symfony Installer is now almost complete!

**Pull request closed without merging**
