### PR TITLE
Add global shorten command for symfony app/console

### PR DESCRIPTION
**Pull request by totophe**
Proposal of a global command shortened for symfony app/console that could be packaged with the symfony installer. It could be then evaluated as a more complete command than just a forwarding command in the future.

### CODE REVIEW

**Comment by futurevision** [comment]
:+1:

**Comment by weaverryan** [comment]
I don't think I like this - it's an extra layer of magic and means there'd be two ways of doing things that you'd find around the web. I could see questions like "what's the difference between `sf` and `app/console`" and also "command `sf` does not exist - how do I install this on my deploy server?"

**Comment by Pierstoval** [comment]
I think like @weaverryan that it's a magic that is not totally needed. You could simply move the `./app/console` file in `./sf` and change the different include paths and it's done.
 
As the `app/console` is already a layer for the console, adding another layer is not much necessary :confused:

**Comment by totophe** [comment]
I think the goal is more to have a global shortcut installed with the symfony-installer that detect if you are in a SF folder and shorten the app/console syntax. But maybe it should be integrated within the ```symfony``` installer and not be an extra command to maintain.

**Comment by Pierstoval** [comment]
I still think it's app-specific, and should not be overriden "natively" by the installer nor by the standard edition itself :confused: 
 
I personally created some "./cs" shortcuts for *nix machines, and a "cs.cmd" for Windows, but it does not always work the expected way because of different shells and versions. For example, shells in Mac and Debian can differ in some small behaviors. But it's, as said, a *personal* choice (and it's only for one project).
 
I'm still :-1: for this, because it adds a new layer for something that is already a layer.

**Comment by futurevision** [comment]
I have to agree with Pierstoval on this one...removed my :+1: for this PR.

**Comment by javiereguiluz** [comment]
Although this proposal is not a bad idea at all, I must close it as *"won't fix"*. It seems that most people think that it has more drawbacks than benefits.

Thank you all for the discussion.

**Pull request closed without merging**
