### PR TITLE
Updated the Symfony versions displayed in README and commands

### PR DESCRIPTION
**Pull request by javiereguiluz**
This supersedes #232.

### CODE REVIEW

**Comment by stof** [comment]
@javiereguiluz can you fix the testsuite ?

**Comment by javiereguiluz** [comment]
The error is caused by the infamous Symfony error that left the `-DEV` suffix in the version number (https://github.com/symfony/symfony/issues/18390 & related). What's the best approach to solve this in our test suite?

**Comment by javiereguiluz** [comment]
Let's merge this as is and then we'll think about how to fix our test suite. Thanks!

**Comment by xabbuh** [comment]
Is it worth to change anything? The failure is not related to the installer but to the built packages and will be good again with the next release.

**Comment by javiereguiluz** [comment]
@xabbuh I think we should fix it because waiting a month is too much and the temporary fix is trivial: https://github.com/symfony/symfony-installer/pull/248

**Pull request merged**
