### PR TITLE
Fix error due to bad file path when installer is located at drive root o...

### PR DESCRIPTION
**Pull request by leto3087**
...n Windows

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@leto3087 thanks for creating this pull request.

Since I don't use Windows, before merging it I'll wait for @WouterJ @sstok and other Windows users to review it. Thanks.

**Comment by WouterJ** [comment]
Seems perfectly valid to me.

Btw, can't we simply use `\\` instead of DIRECTORY_SEPARATOR here? As it's only a problem on Windows, we know it's going to be `\\`.

**Comment by xabbuh** [comment]
The current working directory could end with a backslash on other systems. Even if that's not very likely, we should not introduce any possible issues here by hardcoding `\\` instead of the `DIRECTORY_SEPARATOR` constant.

**Comment by javiereguiluz** [comment]
Everybody seems happy with this PR and the code looks correct, so I'm going to merge it so we can test it in real systems. Thanks @leto3087 for fixing this issue!

**Comment by bluppfisk** [comment]
Problem still exists, Windows 10, using command prompt. Works fine if I use Bash on Windows (Linux Subsystem), but not with the command prompt. Mind, I use C:/wamp64/www/ as my projects directory to allow web-serving through Apache.

```
    5.09 MB/5.09 MB ============================================================  100%

 Preparing project...

  [RuntimeException]
  Symfony can't be installed because the downloaded package is corrupted
  or because the installer doesn't have enough permissions to uncompress and
  rename the package contents.
  To solve this issue, check the permissions of the C:\wamp64\www directory and
  try executing this command again:
  symfony new projectname

  [RuntimeException]
  C:\wamp64\www\projectname does not exist and could not be created.
```

**Pull request merged**
